apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "sh", "-c", "echo Hello from EBS > /data/hello.txt && sleep 3600" ]
    volumeMounts:
    - mountPath: "/data"
      name: ebs-volume
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-pvc
