alertmanager:
  enabled: true
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  persistentVolume:
    enabled: true
    storageClass: "gp2-new"
    size: 2Gi

server:
  enabled: true
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  persistentVolume:
    enabled: true
    storageClass: "gp2-new"
    size: 8Gi

pushgateway:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

serviceAccounts:
  server:
    create: true
  alertmanager:
    create: true

service:
  type: ClusterIP

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
