replicaCount: 1

image:
  repository: '891062950211.dkr.ecr.us-east-1.amazonaws.com/flask-app'
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr-creds

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 5000

readinessProbe:
  httpGet:
    path: /
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes:
  - name: prometheus-server-storage
    persistentVolumeClaim:
      claimName: prometheus-server-pvc

volumeMounts:
  - name: prometheus-server-storage
    mountPath: /data

nodeSelector: {}
tolerations: []
affinity: {}
