- name: Install Observability Stack
  hosts: jenkins
  become: true

  tasks:
    - name: Add Helm repo for Prometheus
      become: false
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Helm repo for Grafana
      become: false
      shell: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Add Helm repo for Fluent Bit
      become: false
      shell: helm repo add fluent https://fluent.github.io/helm-charts

    - name: Update Helm repos
      become: false
      shell: helm repo update

    - name: Install Prometheus
      become: false
      shell: helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace

    - name: Install Grafana
      become: false
      shell: helm upgrade --install grafana grafana/grafana --namespace monitoring --set adminPassword=admin123 --create-namespace

    - name: Install Fluent Bit
      become: false
      shell: helm upgrade --install fluent-bit fluent/fluent-bit --namespace logging --create-namespace
