- name: Add Prometheus Helm repo
  shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

- name: Update Helm repos
  shell: helm repo update

- name: Deploy Prometheus
  shell: |
    helm upgrade --install prometheus prometheus-community/prometheus \
      --namespace monitoring --create-namespace
